export const ADD_MOVIE = "ADD_MOVIE"
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS"
export const ADD_MOVIE_FAILURE = "ADD_MOVIE_FAILURE"

export const GET_LIST_MOVIE_BY_CATEGORY = "GET_LIST_MOVIE_BY_CATEGORY"
export const GET_LIST_MOVIE_BY_CATEGORY_SUCCESS = "GET_LIST_MOVIE_BY_CATEGORY_SUCCESS"
export const GET_LIST_MOVIE_BY_CATEGORY_FAILURE = "GET_LIST_MOVIE_BY_CATEGORY_FAILURE"

export const GET_INFO_MOVIE = "GET_INFO_MOVIE"
export const GET_INFO_MOVIE_SUCCESS = "GET_INFO_MOVIE_SUCCESS"
export const GET_INFO_MOVIE_FAILURE = "GET_INFO_MOVIE_FAILURE"