export const ADD_CATEGORY = "ADD_CATEGORY"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE"

export const GET_LIST_CATEGORY = "GET_LIST_CATEGORY"
export const GET_LIST_CATEGORY_SUCCESS = "GET_LIST_CATEGORY_SUCCESS"
export const GET_LIST_CATEGORY_FAILURE = "GET_LIST_CATEGORY_FAILURE"

export const REMOVE_CATEGORY = "REMOVE_CATEGORY"
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS"
export const REMOVE_CATEGORY_FAILURE = "REMOVE_CATEGORY_FAILURE"

